### ISSUE TITLE
Issue with qwiklabs course

### ISSUE THREAD

**Issue by mkfilipiuk** [GoogleCloudPlatform/gke-binary-auth-demo#17]
Hi,
I"m doing rn a 'Google Kubernetes Engine Security: Binary Authorization' course on qwiklabs and I got an error when I called create.sh script on line:
https://github.com/GoogleCloudPlatform/gke-binary-auth-demo/blob/7d5ca34daca1369a47e586c823b1ff0785394216/create.sh#L44

The error looks like this:
`ERROR: (gcloud.config.set) Section [container] has no property [new_scopes_behavior].`

I've just started learning about GKE, so I don't know why that could happen.

**Comment by bgeesaman** [comment]
That appears to no longer be a valid config flag.  You should be able to safely comment out/delete that line and proceed.

**Comment by mkfilipiuk** [comment]
Ok, I did that. Will you remove it from the source code or maybe I should create a PR?

**Comment by chrislovecnm** [comment]
A PR would be awesome!

**Comment by mkfilipiuk** [comment]
I see that @bgeesaman will handle this:
https://github.com/GoogleCloudPlatform/gke-binary-auth-demo/pull/18
Thanks guys for quick response. I'm closing the issue

**Comment by bgeesaman** [comment]
Thanks for reporting this!
